# Generated by Django 4.1 on 2022-10-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='file',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
