# Generated by Django 4.1 on 2022-10-29 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=1000)),
                ('file', models.ImageField(upload_to='')),
                ('points', models.IntegerField()),
            ],
        ),
    ]
